--SET search_path = public,postgis,swegrg25;


-- Create Schema
CREATE SCHEMA IF NOT EXISTS swegrg25;

-- Set search path to include new schema and PostGIS
SET search_path TO swegrg25, public, postgis;

--Create Sequence statements
CREATE SEQUENCE IF NOT EXISTS swegrg25.org_id_seq;
CREATE SEQUENCE IF NOT EXISTS swegrg25.vo_id_seq;
CREATE SEQUENCE IF NOT EXISTS swegrg25.cs_id_seq;
CREATE SEQUENCE IF NOT EXISTS swegrg25.fb_id_seq;
CREATE SEQUENCE IF NOT EXISTS swegrg25.shelters_cc_id_seq;
CREATE SEQUENCE IF NOT EXISTS swegrg25.med_id_seq;
CREATE SEQUENCE IF NOT EXISTS swegrg25.community_centers_cc_id_seq;
CREATE SEQUENCE IF NOT EXISTS swegrg25.ev_id_seq;
CREATE SEQUENCE IF NOT EXISTS swegrg25.user_id_seq;

-- CREATION OF MAIN TABLES

create table "ENDUSER"
(
    user_data_index bigint     GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 1 CACHE 20) UNIQUE,
    first_name   varchar,
    last_name    varchar,
    username     varchar,
    email_linked varchar,
    password     varchar,
    address      varchar,
    city         varchar,
    state        varchar,
    zip          varchar(5)
);
ALTER TABLE "ENDUSER"
ADD COLUMN eu_data_pk VARCHAR(7) NOT NULL
    GENERATED ALWAYS AS (COALESCE('enus' || user_data_index::text, 'cc_default')) STORED,
ADD CONSTRAINT pk_eu_data_pk PRIMARY KEY (eu_data_pk);


create table "Organization"
(
    org_data_index bigint     GENERATED ALWAYS AS IDENTITY (MINVALUE 0 START WITH 0 CACHE 20) UNIQUE ,
    org_name     varchar UNIQUE,
    user_data_index             bigint,
    address      varchar,
    contact_info varchar,

    CONSTRAINT organization_enduser_fk
            FOREIGN KEY (user_data_index) REFERENCES "ENDUSER" (user_data_index)
);
ALTER TABLE "Organization"
ADD COLUMN org_data_pk VARCHAR(7) NOT NULL
    GENERATED ALWAYS AS (COALESCE('org' || org_data_index::text , 'org_default')) STORED,
ADD CONSTRAINT pk_org_data_pk PRIMARY KEY (org_data_pk);

ALTER TABLE "Organization" OWNER TO postgres;




create table "Volunteer_Opportunities"
(
    vo_data_index   bigint     GENERATED ALWAYS AS IDENTITY (MINVALUE 0 START WITH 0 CACHE 20) UNIQUE ,
    org_name                varchar,
    org_data_index      bigint,
    user_data_index             bigint,
    vo_description      text,
    event_date          timestamp,
    ongoing             boolean,
    requirements        json,
    coordinate_location text,
    address             varchar,
    contact_info        varchar,
    location_notes      text,
    permanent           VARCHAR CHECK (permanent IN ('event', 'volunteer', 'place')),

    CONSTRAINT volunteer_opportunities_table_org_fk
            FOREIGN KEY (org_data_index) REFERENCES "Organization" (org_data_index),

    CONSTRAINT volopp_org_org_name_fk
            FOREIGN KEY (org_name) REFERENCES "Organization"(org_name),

    CONSTRAINT volunteer_opportunities_table_enduser_fk
            FOREIGN KEY (user_data_index) REFERENCES "ENDUSER" (user_data_index)

);
ALTER TABLE "Volunteer_Opportunities"
ADD COLUMN vo_data_pk VARCHAR(7) NOT NULL
    GENERATED ALWAYS AS (COALESCE('voop' || vo_data_index::text, 'voop_default')) STORED,
ADD CONSTRAINT pk_vo_data_pk PRIMARY KEY (vo_data_pk);
ALTER TABLE "Volunteer_Opportunities" OWNER TO postgres;


CREATE OR REPLACE FUNCTION set_org_data_index_in_vo()
RETURNS trigger AS $$
BEGIN
   SELECT org_data_index INTO NEW.org_data_index
   FROM swegrg25."Organization"
   WHERE swegrg25."Organization".org_name = NEW.org_name
   LIMIT 1;

   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_org_data_index
BEFORE INSERT ON "Volunteer_Opportunities"
FOR EACH ROW
EXECUTE FUNCTION set_org_data_index_in_vo();


create table "Clothing_Stores"
(
    cs_data_index bigint     GENERATED ALWAYS AS IDENTITY (MINVALUE 0 START WITH 0 CACHE 20),
    org_name                varchar,
    org_data_index      bigint,
    user_data_index             bigint,
    price_range         varchar
        constraint "Clothing_Stores_price_range_check"
            check ((price_range)::text = ANY
                   ((ARRAY ['Free'::character varying, 'Low-Cost'::character varying, 'Mixed'::character varying])::text[])),
    hours_of_operation  json,
    address             varchar,
    contact_info        varchar,
    coordinate_location text,
    location_notes      text,
    permanent           VARCHAR CHECK (permanent IN ('event', 'volunteer', 'place')),

    CONSTRAINT clothing_stores_table_org_fk
            FOREIGN KEY (org_data_index) REFERENCES "Organization" (org_data_index),

    CONSTRAINT clothing_org_org_name_fk
            FOREIGN KEY (org_name) REFERENCES "Organization"(org_name),

    CONSTRAINT clothing_stores_table_enduser_fk
            FOREIGN KEY (user_data_index) REFERENCES "ENDUSER" (user_data_index)
);

ALTER TABLE "Clothing_Stores"
ADD COLUMN cs_data_pk VARCHAR(7) NOT NULL
    GENERATED ALWAYS AS (COALESCE('clst' || cs_data_index::text, 'clst_default')) STORED,
ADD CONSTRAINT pk_cs_data_pk PRIMARY KEY (cs_data_pk);
ALTER TABLE "Clothing_Stores" OWNER TO postgres;

CREATE OR REPLACE FUNCTION set_org_data_index_in_cs()
RETURNS trigger AS $$
BEGIN
   SELECT org_data_index INTO NEW.org_data_index
   FROM swegrg25."Organization"
   WHERE swegrg25."Organization".org_name = NEW.org_name
   LIMIT 1;

   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_org_data_index
BEFORE INSERT ON "Clothing_Stores"
FOR EACH ROW
EXECUTE FUNCTION set_org_data_index_in_cs();

create table "Food_Banks"
(
    fb_data_index bigint     GENERATED ALWAYS AS IDENTITY (MINVALUE 0 START WITH 0 CACHE 20),
    org_name                varchar,
    org_data_index      bigint,
    user_data_index             bigint,
    accommodation_limit integer,
    hours_of_operation  json,
    coordinate_location text,
    address             varchar,
    contact_info        varchar,
    location_notes      json,
    permanent           VARCHAR CHECK (permanent IN ('event', 'volunteer', 'place')),

    CONSTRAINT food_banks_table_org_fk
            FOREIGN KEY (org_data_index) REFERENCES "Organization" (org_data_index),

    CONSTRAINT food_org_org_name_fk
            FOREIGN KEY (org_name) REFERENCES "Organization"(org_name),

    CONSTRAINT food_banks_table_enduser_fk
            FOREIGN KEY (user_data_index) REFERENCES "ENDUSER" (user_data_index)
);
ALTER TABLE "Food_Banks"
ADD COLUMN fb_data_pk VARCHAR(7) NOT NULL
    GENERATED ALWAYS AS (COALESCE('foba' || fb_data_index::text, 'foba_default')) STORED,
ADD CONSTRAINT pk_fb_data_pk PRIMARY KEY (fb_data_pk);
ALTER TABLE "Food_Banks" OWNER TO postgres;


CREATE OR REPLACE FUNCTION set_org_data_index_in_fb()
RETURNS trigger AS $$
BEGIN
   SELECT org_data_index INTO NEW.org_data_index
   FROM swegrg25."Organization"
   WHERE swegrg25."Organization".org_name = NEW.org_name
   LIMIT 1;

   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_org_data_index
BEFORE INSERT ON "Food_Banks"
FOR EACH ROW
EXECUTE FUNCTION set_org_data_index_in_fb();


create table "Shelters"
(
    sh_data_index bigint     GENERATED ALWAYS AS IDENTITY (MINVALUE 0 START WITH 0 CACHE 20),
    org_name                varchar,
    org_data_index      bigint,
    user_data_index             bigint,
    space_available     integer,
    maximum_capacity    integer,
    hours_of_operation  json,
    address             varchar,
    contact_info        varchar,
    coordinate_location text,
    location_notes      json,
    permanent           VARCHAR CHECK (permanent IN ('event', 'volunteer', 'place')),

    CONSTRAINT shelters_table_org_fk
            FOREIGN KEY (org_data_index) REFERENCES "Organization" (org_data_index),

    CONSTRAINT shelters_org_org_name_fk
            FOREIGN KEY (org_name) REFERENCES "Organization"(org_name),
    CONSTRAINT shelters_table_enduser_fk
            FOREIGN KEY (user_data_index) REFERENCES "ENDUSER" (user_data_index)
);
ALTER TABLE "Shelters"
ADD COLUMN sh_data_pk VARCHAR(7) NOT NULL
    GENERATED ALWAYS AS (COALESCE('shelt' || sh_data_index::text, 'shelt_default')) STORED,
ADD CONSTRAINT pk_sh_data_pk PRIMARY KEY (sh_data_pk);
ALTER TABLE "Shelters" OWNER TO postgres;

CREATE OR REPLACE FUNCTION set_org_data_index_in_s()
RETURNS trigger AS $$
BEGIN
   SELECT org_data_index INTO NEW.org_data_index
   FROM swegrg25."Organization"
   WHERE swegrg25."Organization".org_name = NEW.org_name
   LIMIT 1;

   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_org_data_index
BEFORE INSERT ON "Shelters"
FOR EACH ROW
EXECUTE FUNCTION set_org_data_index_in_s();

create table "Med_Centers"
(
    med_data_index bigint     GENERATED ALWAYS AS IDENTITY (MINVALUE 0 START WITH 0 CACHE 20),
    org_name                varchar,
    org_data_index      bigint,
    user_data_index             bigint,
    average_wait_time   integer,
    address             varchar,
    contact_info        varchar,
    services_provided   json,
    coordinate_location text,
    location_notes      json,
    permanent           VARCHAR CHECK (permanent IN ('event', 'volunteer', 'place')),

    CONSTRAINT med_centers_table_org_fk
            FOREIGN KEY (org_data_index) REFERENCES "Organization" (org_data_index),

    CONSTRAINT med_org_org_name_fk
            FOREIGN KEY (org_name) REFERENCES "Organization"(org_name),

    CONSTRAINT med_centers_table_enduser_fk
            FOREIGN KEY (user_data_index) REFERENCES "ENDUSER" (user_data_index)
);
ALTER TABLE "Med_Centers"
ADD COLUMN med_data_pk VARCHAR(7) NOT NULL
    GENERATED ALWAYS AS (COALESCE('med' || med_data_index::text, 'med_default')) STORED,
ADD CONSTRAINT pk_med_data_pk PRIMARY KEY (med_data_pk);
ALTER TABLE "Med_Centers" OWNER TO postgres;


CREATE OR REPLACE FUNCTION set_org_data_index_in_mc()
RETURNS trigger AS $$
BEGIN
   SELECT org_data_index INTO NEW.org_data_index
   FROM swegrg25."Organization"
   WHERE swegrg25."Organization".org_name = NEW.org_name
   LIMIT 1;

   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_org_data_index
BEFORE INSERT ON "Med_Centers"
FOR EACH ROW
EXECUTE FUNCTION set_org_data_index_in_mc();

create table "Community_Centers"
(
    cc_data_index bigint     GENERATED ALWAYS AS IDENTITY (MINVALUE 0 START WITH 0 CACHE 20),
    org_name                varchar,
    org_data_index      bigint,
    user_data_index             bigint,
    hours_of_operation  json,
    coordinate_location text,
    address             varchar,
    contact_info        varchar,
    offered_services    json,
    location_notes      text,
    permanent           VARCHAR CHECK (permanent IN ('event', 'volunteer', 'place')),

    CONSTRAINT community_centers_table_org_fk
            FOREIGN KEY (org_data_index) REFERENCES "Organization" (org_data_index),

    CONSTRAINT center_org_org_name_fk
            FOREIGN KEY (org_name) REFERENCES "Organization"(org_name),

    CONSTRAINT community_centers_table_enduser_fk
            FOREIGN KEY (user_data_index) REFERENCES "ENDUSER" (user_data_index)
);
ALTER TABLE "Community_Centers"
ADD COLUMN cc_data_pk VARCHAR(7) NOT NULL
    GENERATED ALWAYS AS (COALESCE('cc' || cc_data_index::text, 'cc_default')) STORED,
ADD CONSTRAINT pk_cc_data_pk PRIMARY KEY (cc_data_pk);
ALTER TABLE "Community_Centers" OWNER TO postgres;

CREATE OR REPLACE FUNCTION set_org_data_index_in_cc()
RETURNS trigger AS $$
BEGIN
   SELECT org_data_index INTO NEW.org_data_index
   FROM swegrg25."Organization"
   WHERE swegrg25."Organization".org_name = NEW.org_name
   LIMIT 1;

   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_org_data_index
BEFORE INSERT ON "Community_Centers"
FOR EACH ROW
EXECUTE FUNCTION set_org_data_index_in_cc();



create table "Community_Events"
(
    e_data_index bigint     GENERATED ALWAYS AS IDENTITY (MINVALUE 0 START WITH 0 CACHE 20),
    name                varchar,
    description         text,
    event_date          timestamp,
    user_data_index             bigint,
    address             varchar,
    contact_info        varchar,
    category            text,
    attendee_count      integer,
    coordinate_location text,
    location_notes      text,
    permanent           VARCHAR CHECK (permanent IN ('event', 'volunteer', 'place')),

    CONSTRAINT community_events_table_enduser_fk
            FOREIGN KEY (user_data_index) REFERENCES "ENDUSER" (user_data_index)
);
ALTER TABLE "Community_Events"
ADD COLUMN e_data_pk VARCHAR(7) NOT NULL
    GENERATED ALWAYS AS (COALESCE('ce' || e_data_index::text, 'ce_default')) STORED,
ADD CONSTRAINT pk_e_data_pk PRIMARY KEY (e_data_pk);
ALTER TABLE "Community_Events"
ADD CONSTRAINT unique_e_data_index UNIQUE (e_data_index);
ALTER TABLE "Community_Events" OWNER TO postgres;

create table "USER_TYPES"
(
    user_type        varchar not null
        constraint user_types_table_pk
            primary key,
    type_abbrev      varchar,
    type_description text
);

create table "LOG_User_Login"
(
    user_data_index bigint default nextval('swegrg25.user_id_seq'::regclass) not null,
    timelogged      timestamp,
    account_name    varchar(255)                                              not null,
    hashed_password varchar(255)                                              not null,
    security_token  varchar(255),
    user_type       text
        constraint "LOG_User_Login_user_type_check"
            check (user_type = ANY (ARRAY ['EndUser'::text, 'Volunteer'::text, 'Organizer'::text, 'Admin'::text])),

    CONSTRAINT log_user_login_enduser_fk
        FOREIGN KEY (user_data_index) REFERENCES "ENDUSER" (user_data_index)
);
alter table "LOG_User_Login"
    owner to postgres;

create table "LOG_User_Info_Queue"
(
    user_data_index      bigint default nextval('swegrg25.user_id_seq'::regclass) not null,
    timelogged   timestamp,
    first_name   varchar,
    last_name    varchar,
    username     varchar,
    email_linked varchar,
    password     varchar,
    address      varchar,
    city         varchar,
    state        varchar,
    zip          varchar(5),

    CONSTRAINT log_user_login_enduser_fk
        FOREIGN KEY (user_data_index) REFERENCES "ENDUSER" (user_data_index)
);
alter table "LOG_User_Info_Queue"
    owner to postgres;

create table "Volunteers"
(
    vo_data_index   bigint default nextval('swegrg25.vo_id_seq'::regclass) not null
        constraint volunteers_pk
            primary key,
    user_data_index bigint not null,

    CONSTRAINT log_user_login_enduser_fk
        FOREIGN KEY (user_data_index) REFERENCES "ENDUSER" (user_data_index),

    CONSTRAINT volunteers_volunteer_opportunities_vo_id_fk
            FOREIGN KEY (vo_data_index) REFERENCES "Volunteer_Opportunities" (vo_data_index)
);
alter table "Volunteers"
    owner to postgres;

CREATE TABLE "Save_Resource"
(
    user_data_index BIGINT NOT NULL,
    resource_data_pk VARCHAR(10) NOT NULL,  -- e.g., 'clst001', 'foba003', etc.
    saved_at TIMESTAMP DEFAULT now(),
    user_category VARCHAR(100),

    CONSTRAINT save_resource_pk PRIMARY KEY (user_data_index, resource_data_pk),

    CONSTRAINT save_resource_user_fk FOREIGN KEY (user_data_index)
        REFERENCES "ENDUSER" (user_data_index)
        ON DELETE CASCADE
);
ALTER TABLE "Save_Resource" owner to postgres;


comment on table "Volunteers" is 'This would map what volunteers are connected to what events. Junction Table: many-to-many';

